name: Transfer data between jobs
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      steps: ${{steps.job1_output.outputs }}
    steps:
      - name: Set Variable in Job 1
        id: job1_output
        run: |
          echo "AGENT_IP= 172.64.0.0.1" >> $GITHUB_ENV
          echo "::set-output name=AGENT_IP::your-agent-ip"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Show Variable in Job 2
        run: echo "AGENT_IP=${{ needs.job1.job1_outputs.AGENT_IP }}"

